modules:
  baltop:
    interval: 200L
    noplayer: "unknown"
    updateOffline: true
    size: 10


papi:
  "%statistic_seconds_played%":  # Change this crap
    interval: 200L
    noplayer: "unknown"
    updateOffline: true
    size: 10
    type: "time"
