# plugin developed by Gasper Lukman
# https://github.com/NeutralPlasma/HoloExtension
# All rights reserved to Gasper Lukman
# Support discord server: https://discord.gg/Zpks2WK
#
# for each placeholder replace # with position for example
# {he-baltop-1-user} {he-baltop-2-user} {he-baltop-3-user}

version: @version@

system:
  storage_type: "SQL"
  # SQL or MySQL

  #mysql configuration
  username: "root"
  password: "password"
  server: "127.0.0.1"
  port: 3306
  useSSL: false
  database: "example"

modules:
  # baltop module
  # placeholders:
  # {he-baltop-#-user}
  # {he-baltop-#-value}
  baltop:
    updateOffline: true
    enabled: true
    format: 3

  # protocollib module:
  # placeholders:
  # {slow} - 10 seconds
  # {medium} - 1 second
  # {fast} - 0.1 second
  ProtocolLib:
    enabled: true


papi:
  # Example papi module
  # placeholders
  # {he-%statistic_seconds_played%-#-user}
  # {he-%statistic_seconds_played%-#-value}
  "%statistic_seconds_played%":  # Change this crap
    updateOffline: true
    size: 10
    enabled: true
    format: 4
