name: HoloExtension
main: eu.virtusdevelops.holoextension.HoloExtension
version: @version@
api-version: "1.13"
author: NeutralPlasma

depend: [Vault]
softdepend:
  - PlaceholderAPI
  - HolographicDisplays
  - ProtocolLib


commands:
  he:
    aliases: [he]
    permission: holoextension.command.main
    usage: /<command>

